language: python
python: # all the python 3 versions for fun!
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies

script:
  - python setup.py test